name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: mvn --batch-mode --update-snapshots verify
      - run: mvn javadoc:javadoc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apidocs
  javadoc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
permissions:
  contents: read
  pages: write
  id-token: write
